#!/bin/bash
#               LAUNCH STANDART MODE GNOME DE
#
top_bar_enabled=$(gsettings get org.gnome.shell.extensions.just-perfection panel)
current_wallpaper=$(gsettings get org.gnome.desktop.background picture-uri)
current_wallpaper_dark=$(gsettings get org.gnome.desktop.background picture-uri-dark)
current_volume=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -oP '\d+%' | head -1)
check_monitor_active=$(xrandr --listactivemonitors | grep DP-4)
notification_enabled=$(gsettings get org.gnome.desktop.notifications show-banners)
browser_name=$(wmctrl -lx | grep "firefox" | awk '{print $5}')


notify-send "STANDARD MODE ACTIVATED" --icon=bell --app-name="Home" "Welcome Home!"
# gsettings set org.gnome.desktop.notifications show-banners true &
# echo "Notifications are turned on."


#-------------------------------------------------------------------------------------
# if [ -n "$check_monitor_active" ]; then
#   gsettings set org.gnome.desktop.notifications show-banners true &
#   toggle-monitors &
#   wait
#   sleep 4
# fi
#-------------------------------------------------------------------------------------
# Check and start conky files
if ! pgrep "conky" >/dev/null; then
  echo "Conky starting ..."
  conky -c ~/.config/conky/Botein/Botein.conf >/dev/null 2>&1 &
  conky -c ~/.config/conky/Sadachbia-DarkF-v2.0\(1\)/Sadachbia-Dark/Sadachbia-Dark.conf >/dev/null 2>&1 &
fi

#-------------------------------------------------------------------------------------
# Check if status Area Horizontal Spacing is disable and enable it
#
# if ! gnome-extensions info status-area-horizontal-spacing@mathematical.coffee.gmail.com | grep -q "State: ACTIVE" ; then
#     echo "Enable Status Area Horizontal Spacing ..."
#     gnome-extensions enable status-area-horizontal-spacing@mathematical.coffee.gmail.com
# fi

# Change user theme if it's not already set
# current_theme=$(gsettings get org.gnome.shell.extensions.user-theme name)
# if [ "$current_theme" != "test" ]; then
#     echo "Changing user theme to 'test' ..."
#     gsettings set org.gnome.shell.extensions.user-theme name 'test'
# fi
#-------------------------------------------------------------------------------------
#
##  Define extension IDs and names
extensions=(
    "appindicatorsupport@rgcjonas.gmail.com:AppIndicator & KStatusNotifierItem"
    "gsconnect@andyholmes.github.io:GSConnect"
    "quick-settings-tweaks@qwreey:Quick Setting Tweaker"
    "dash-to-dock@micxgx.gmail.com:dash-to-dock"
)

# Loop through extensions
for ext in "${extensions[@]}"; do
    ext_id="${ext%%:*}"  # Extract extension ID
    ext_name="${ext#*:}"  # Extract extension name

    # Check if extension is active and disable it
    if ! gnome-extensions info "$ext_id" | grep -q "State: ACTIVE"; then
        gnome-extensions enable "$ext_id"
        echo "Enabling $ext_name ..."
        sleep 0.08
    fi
done
#-------------------------------------------------------------------------------------
#
# Check if AppIndicator is disable and enable it
# if ! gnome-extensions info appindicatorsupport@rgcjonas.gmail.com | grep -q "State: ACTIVE" ; then
#     gnome-extensions enable appindicatorsupport@rgcjonas.gmail.com
#     echo "Enable AppIndicator & KStatusNotifierItem ..."
# fi
#
#-------------------------------------------------------------------------------------
if [ "$notification_enabled" != "true" ]; then
    gsettings set org.gnome.desktop.notifications show-banners 'true' 
    echo "Notifications are turned on."
    sleep 0.08
fi

#   Enable GNOME top bar if it's not already enable
if [ "$top_bar_enabled" != "true" ]; then
    gsettings set org.gnome.shell.extensions.just-perfection panel 'true'
    echo "Enabling Gnome top bar ..."
    sleep 0.08
fi
#-------------------------------------------------------------------------------------

#   Change wallpaper for dark mode if it's not already set
if [ "$current_wallpaper_dark" != "'file://$HOME/.local/share/backgrounds/nordnew/nordnew-d.png'" ]; then
    gsettings set org.gnome.desktop.background picture-uri-dark "file://$HOME/.local/share/backgrounds/nordnew/nordnew-d.png"
    echo "Setting dark mode wallpaper ..."
fi
#-------------------------------------------------------------------------------------
#   Change wallpaper for light mode if it's not already set
if [ "$current_wallpaper" != "'file://$HOME/.local/share/backgrounds/nordnew/nordnew-l.png'" ]; then
    gsettings set org.gnome.desktop.background picture-uri "file://$HOME/.local/share/backgrounds/nordnew/nordnew-l.png"
    echo "Setting light mode wallpaper ..."
fi
#-------------------------------------------------------------------------------------
#   Set volume to 50% if it's not already set
if [ "$current_volume" != "50%" ]; then
    pactl set-sink-volume @DEFAULT_SINK@ 50%
    echo "Setting volume to 50% ..."
    sleep 0.08
fi

if [ -n "$browser_name" ]; then
  wmctrl -l | grep -vE "Tilix|$browser_name|conky" | awk '{print $1}' | xargs -I {} wmctrl -ic {}
else
  wmctrl -l | grep -vE "Tilix|conky" | awk '{print $1}' | xargs -I {} wmctrl -ic {}
  firefox >/dev/null 2>&1 &
  echo "Firefox is starting ..."
fi


#-------------------------------------------------------------------------------------
echo "Standard Mode Activated. Good Luck Mate!"
